window.BOLAO_DATA = {
  "settings": {
    "title": "Bolão Copa 2026",
    "exactScorePoints": 3,
    "resultPoints": 1,
    "entryFee": 20.0,
    "prizeWinners": 4,
    "lockMinutesBeforeRound": 15,
    "showPicksBeforeDeadline": false,
    "apiUrl": "https://script.google.com/macros/s/AKfycbyznSo37nnchBRTJNl49gZoE5Q0w8jpb_fvLS12dK0ll7RjQcSv2mzYNfjMiC-BLGWa_g/exec"
  },
  "players": [
    {
      "id": "andrey",
      "name": "Andrey",
      "paid": false
    },
    {
      "id": "arthur",
      "name": "Arthur",
      "paid": false
    },
    {
      "id": "broca",
      "name": "Broca",
      "paid": false
    },
    {
      "id": "charlie",
      "name": "Charlie",
      "paid": false
    },
    {
      "id": "lucao",
      "name": "Lucão",
      "paid": false
    },
    {
      "id": "matchaca",
      "name": "Matchaca",
      "paid": false
    },
    {
      "id": "matzilla",
      "name": "Matzilla",
      "paid": false
    },
    {
      "id": "pedrao",
      "name": "Pedrão",
      "paid": false
    },
    {
      "id": "gean",
      "name": "Gean",
      "paid": false
    },
    {
      "id": "murilo",
      "name": "Murilo",
      "paid": false
    },
    {
      "id": "kashima",
      "name": "Kashima",
      "paid": false
    }
  ],
  "groups": [
    {
      "id": "A",
      "name": "Grupo A",
      "teams": [
        "África do Sul",
        "Coreia do Sul",
        "México",
        "República Tcheca"
      ]
    },
    {
      "id": "B",
      "name": "Grupo B",
      "teams": [
        "Bósnia",
        "Canadá",
        "Catar",
        "Suíça"
      ]
    },
    {
      "id": "C",
      "name": "Grupo C",
      "teams": [
        "Brasil",
        "Escócia",
        "Haiti",
        "Marrocos"
      ]
    },
    {
      "id": "D",
      "name": "Grupo D",
      "teams": [
        "Austrália",
        "Estados Unidos",
        "Paraguai",
        "Turquia"
      ]
    },
    {
      "id": "E",
      "name": "Grupo E",
      "teams": [
        "Alemanha",
        "Costa do Marfim",
        "Curaçao",
        "Equador"
      ]
    },
    {
      "id": "F",
      "name": "Grupo F",
      "teams": [
        "Holanda",
        "Japão",
        "Suécia",
        "Tunísia"
      ]
    },
    {
      "id": "G",
      "name": "Grupo G",
      "teams": [
        "Bélgica",
        "Egito",
        "Irã",
        "Nova Zelândia"
      ]
    },
    {
      "id": "H",
      "name": "Grupo H",
      "teams": [
        "Arábia Saudita",
        "Cabo Verde",
        "Espanha",
        "Uruguai"
      ]
    },
    {
      "id": "I",
      "name": "Grupo I",
      "teams": [
        "França",
        "Iraque",
        "Noruega",
        "Senegal"
      ]
    },
    {
      "id": "J",
      "name": "Grupo J",
      "teams": [
        "Argélia",
        "Argentina",
        "Áustria",
        "Jordânia"
      ]
    },
    {
      "id": "K",
      "name": "Grupo K",
      "teams": [
        "Colômbia",
        "RD Congo",
        "Portugal",
        "Uzbequistão"
      ]
    },
    {
      "id": "L",
      "name": "Grupo L",
      "teams": [
        "Croácia",
        "Gana",
        "Inglaterra",
        "Panamá"
      ]
    }
  ],
  "matches": [
    {
      "id": "J001",
      "number": 1,
      "round": "Rodada 1",
      "group": "Grupo A",
      "date": "2026-06-11",
      "time": "16:00",
      "venue": "Estadio Azteca - MEX",
      "team1": "México",
      "team2": "África do Sul",
      "score1": null,
      "score2": null
    },
    {
      "id": "J002",
      "number": 2,
      "round": "Rodada 1",
      "group": "Grupo A",
      "date": "2026-06-11",
      "time": "23:00",
      "venue": "Estadio Akron - MEX",
      "team1": "Coreia do Sul",
      "team2": "República Tcheca",
      "score1": null,
      "score2": null
    },
    {
      "id": "J003",
      "number": 3,
      "round": "Rodada 1",
      "group": "Grupo B",
      "date": "2026-06-12",
      "time": "16:00",
      "venue": "BMO Field - CAN",
      "team1": "Canadá",
      "team2": "Bósnia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J004",
      "number": 4,
      "round": "Rodada 1",
      "group": "Grupo D",
      "date": "2026-06-12",
      "time": "22:00",
      "venue": "SoFi Stadium - EUA",
      "team1": "Estados Unidos",
      "team2": "Paraguai",
      "score1": null,
      "score2": null
    },
    {
      "id": "J005",
      "number": 5,
      "round": "Rodada 1",
      "group": "Grupo B",
      "date": "2026-06-13",
      "time": "16:00",
      "venue": "Levi's Stadium - EUA",
      "team1": "Catar",
      "team2": "Suíça",
      "score1": null,
      "score2": null
    },
    {
      "id": "J006",
      "number": 6,
      "round": "Rodada 1",
      "group": "Grupo C",
      "date": "2026-06-13",
      "time": "19:00",
      "venue": "MetLife Stadium - EUA",
      "team1": "Brasil",
      "team2": "Marrocos",
      "score1": null,
      "score2": null
    },
    {
      "id": "J007",
      "number": 7,
      "round": "Rodada 1",
      "group": "Grupo C",
      "date": "2026-06-13",
      "time": "22:00",
      "venue": "Gillette Stadium - EUA",
      "team1": "Haiti",
      "team2": "Escócia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J008",
      "number": 8,
      "round": "Rodada 1",
      "group": "Grupo D",
      "date": "2026-06-14",
      "time": "01:00",
      "venue": "BC Place - CAN",
      "team1": "Austrália",
      "team2": "Turquia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J009",
      "number": 9,
      "round": "Rodada 1",
      "group": "Grupo E",
      "date": "2026-06-14",
      "time": "14:00",
      "venue": "NRG Stadium - EUA",
      "team1": "Alemanha",
      "team2": "Curaçao",
      "score1": null,
      "score2": null
    },
    {
      "id": "J010",
      "number": 10,
      "round": "Rodada 1",
      "group": "Grupo F",
      "date": "2026-06-14",
      "time": "17:00",
      "venue": "AT&T Stadium - EUA",
      "team1": "Holanda",
      "team2": "Japão",
      "score1": null,
      "score2": null
    },
    {
      "id": "J011",
      "number": 11,
      "round": "Rodada 1",
      "group": "Grupo E",
      "date": "2026-06-14",
      "time": "20:00",
      "venue": "Lincoln Financial - EUA",
      "team1": "Costa do Marfim",
      "team2": "Equador",
      "score1": null,
      "score2": null
    },
    {
      "id": "J012",
      "number": 12,
      "round": "Rodada 1",
      "group": "Grupo F",
      "date": "2026-06-14",
      "time": "23:00",
      "venue": "Estadio BBVA - MEX",
      "team1": "Suécia",
      "team2": "Tunísia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J013",
      "number": 13,
      "round": "Rodada 1",
      "group": "Grupo H",
      "date": "2026-06-15",
      "time": "13:00",
      "venue": "Mercedes-Benz - EUA",
      "team1": "Espanha",
      "team2": "Cabo Verde",
      "score1": null,
      "score2": null
    },
    {
      "id": "J014",
      "number": 14,
      "round": "Rodada 1",
      "group": "Grupo G",
      "date": "2026-06-15",
      "time": "16:00",
      "venue": "Lumen Field - EUA",
      "team1": "Bélgica",
      "team2": "Egito",
      "score1": null,
      "score2": null
    },
    {
      "id": "J015",
      "number": 15,
      "round": "Rodada 1",
      "group": "Grupo H",
      "date": "2026-06-15",
      "time": "19:00",
      "venue": "Hard Rock - EUA",
      "team1": "Arábia Saudita",
      "team2": "Uruguai",
      "score1": null,
      "score2": null
    },
    {
      "id": "J016",
      "number": 16,
      "round": "Rodada 1",
      "group": "Grupo G",
      "date": "2026-06-15",
      "time": "22:00",
      "venue": "SoFi Stadium - EUA",
      "team1": "Irã",
      "team2": "Nova Zelândia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J017",
      "number": 17,
      "round": "Rodada 1",
      "group": "Grupo I",
      "date": "2026-06-16",
      "time": "16:00",
      "venue": "MetLife Stadium - EUA",
      "team1": "França",
      "team2": "Senegal",
      "score1": null,
      "score2": null
    },
    {
      "id": "J018",
      "number": 18,
      "round": "Rodada 1",
      "group": "Grupo I",
      "date": "2026-06-16",
      "time": "19:00",
      "venue": "Gillette Stadium - EUA",
      "team1": "Iraque",
      "team2": "Noruega",
      "score1": null,
      "score2": null
    },
    {
      "id": "J019",
      "number": 19,
      "round": "Rodada 1",
      "group": "Grupo J",
      "date": "2026-06-16",
      "time": "22:00",
      "venue": "Arrowhead Stadium - EUA",
      "team1": "Argentina",
      "team2": "Argélia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J020",
      "number": 20,
      "round": "Rodada 1",
      "group": "Grupo J",
      "date": "2026-06-17",
      "time": "01:00",
      "venue": "Levi's Stadium - EUA",
      "team1": "Áustria",
      "team2": "Jordânia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J021",
      "number": 21,
      "round": "Rodada 1",
      "group": "Grupo K",
      "date": "2026-06-17",
      "time": "14:00",
      "venue": "NRG Stadium - EUA",
      "team1": "Portugal",
      "team2": "RD Congo",
      "score1": null,
      "score2": null
    },
    {
      "id": "J022",
      "number": 22,
      "round": "Rodada 1",
      "group": "Grupo L",
      "date": "2026-06-17",
      "time": "17:00",
      "venue": "AT&T Stadium - EUA",
      "team1": "Inglaterra",
      "team2": "Croácia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J023",
      "number": 23,
      "round": "Rodada 1",
      "group": "Grupo L",
      "date": "2026-06-17",
      "time": "20:00",
      "venue": "BMO Field - CAN",
      "team1": "Gana",
      "team2": "Panamá",
      "score1": null,
      "score2": null
    },
    {
      "id": "J024",
      "number": 24,
      "round": "Rodada 1",
      "group": "Grupo K",
      "date": "2026-06-17",
      "time": "23:00",
      "venue": "Estadio Azteca - MEX",
      "team1": "Uzbequistão",
      "team2": "Colômbia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J025",
      "number": 25,
      "round": "Rodada 2",
      "group": "Grupo A",
      "date": "2026-06-18",
      "time": "13:00",
      "venue": "Mercedes-Benz - EUA",
      "team1": "República Tcheca",
      "team2": "África do Sul",
      "score1": null,
      "score2": null
    },
    {
      "id": "J026",
      "number": 26,
      "round": "Rodada 2",
      "group": "Grupo B",
      "date": "2026-06-18",
      "time": "16:00",
      "venue": "SoFi Stadium - EUA",
      "team1": "Suíça",
      "team2": "Bósnia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J027",
      "number": 27,
      "round": "Rodada 2",
      "group": "Grupo B",
      "date": "2026-06-18",
      "time": "19:00",
      "venue": "BC Place - CAN",
      "team1": "Canadá",
      "team2": "Catar",
      "score1": null,
      "score2": null
    },
    {
      "id": "J028",
      "number": 28,
      "round": "Rodada 2",
      "group": "Grupo A",
      "date": "2026-06-18",
      "time": "22:00",
      "venue": "Estadio Akron - MEX",
      "team1": "México",
      "team2": "Coreia do Sul",
      "score1": null,
      "score2": null
    },
    {
      "id": "J029",
      "number": 29,
      "round": "Rodada 2",
      "group": "Grupo D",
      "date": "2026-06-19",
      "time": "16:00",
      "venue": "Lumen Field - EUA",
      "team1": "Estados Unidos",
      "team2": "Austrália",
      "score1": null,
      "score2": null
    },
    {
      "id": "J030",
      "number": 30,
      "round": "Rodada 2",
      "group": "Grupo C",
      "date": "2026-06-19",
      "time": "19:00",
      "venue": "Gillette Stadium - EUA",
      "team1": "Escócia",
      "team2": "Marrocos",
      "score1": null,
      "score2": null
    },
    {
      "id": "J031",
      "number": 31,
      "round": "Rodada 2",
      "group": "Grupo C",
      "date": "2026-06-19",
      "time": "21:30",
      "venue": "Lincoln Financial - EUA",
      "team1": "Brasil",
      "team2": "Haiti",
      "score1": null,
      "score2": null
    },
    {
      "id": "J032",
      "number": 32,
      "round": "Rodada 2",
      "group": "Grupo D",
      "date": "2026-06-20",
      "time": "00:00",
      "venue": "Levi's Stadium - EUA",
      "team1": "Turquia",
      "team2": "Paraguai",
      "score1": null,
      "score2": null
    },
    {
      "id": "J033",
      "number": 33,
      "round": "Rodada 2",
      "group": "Grupo F",
      "date": "2026-06-20",
      "time": "14:00",
      "venue": "NRG Stadium - EUA",
      "team1": "Holanda",
      "team2": "Suécia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J034",
      "number": 34,
      "round": "Rodada 2",
      "group": "Grupo E",
      "date": "2026-06-20",
      "time": "17:00",
      "venue": "BMO Field - CAN",
      "team1": "Alemanha",
      "team2": "Costa do Marfim",
      "score1": null,
      "score2": null
    },
    {
      "id": "J035",
      "number": 35,
      "round": "Rodada 2",
      "group": "Grupo E",
      "date": "2026-06-20",
      "time": "21:00",
      "venue": "Arrowhead Stadium - EUA",
      "team1": "Equador",
      "team2": "Curaçao",
      "score1": null,
      "score2": null
    },
    {
      "id": "J036",
      "number": 36,
      "round": "Rodada 2",
      "group": "Grupo F",
      "date": "2026-06-21",
      "time": "01:00",
      "venue": "Estadio BBVA - MEX",
      "team1": "Tunísia",
      "team2": "Japão",
      "score1": null,
      "score2": null
    },
    {
      "id": "J037",
      "number": 37,
      "round": "Rodada 2",
      "group": "Grupo H",
      "date": "2026-06-21",
      "time": "13:00",
      "venue": "Mercedes-Benz - EUA",
      "team1": "Espanha",
      "team2": "Arábia Saudita",
      "score1": null,
      "score2": null
    },
    {
      "id": "J038",
      "number": 38,
      "round": "Rodada 2",
      "group": "Grupo G",
      "date": "2026-06-21",
      "time": "16:00",
      "venue": "SoFi Stadium - EUA",
      "team1": "Bélgica",
      "team2": "Irã",
      "score1": null,
      "score2": null
    },
    {
      "id": "J039",
      "number": 39,
      "round": "Rodada 2",
      "group": "Grupo H",
      "date": "2026-06-21",
      "time": "19:00",
      "venue": "Hard Rock - EUA",
      "team1": "Uruguai",
      "team2": "Cabo Verde",
      "score1": null,
      "score2": null
    },
    {
      "id": "J040",
      "number": 40,
      "round": "Rodada 2",
      "group": "Grupo G",
      "date": "2026-06-21",
      "time": "22:00",
      "venue": "BC Place - CAN",
      "team1": "Nova Zelândia",
      "team2": "Egito",
      "score1": null,
      "score2": null
    },
    {
      "id": "J041",
      "number": 41,
      "round": "Rodada 2",
      "group": "Grupo J",
      "date": "2026-06-22",
      "time": "14:00",
      "venue": "AT&T Stadium - EUA",
      "team1": "Argentina",
      "team2": "Áustria",
      "score1": null,
      "score2": null
    },
    {
      "id": "J042",
      "number": 42,
      "round": "Rodada 2",
      "group": "Grupo I",
      "date": "2026-06-22",
      "time": "18:00",
      "venue": "Lincoln Financial - EUA",
      "team1": "França",
      "team2": "Iraque",
      "score1": null,
      "score2": null
    },
    {
      "id": "J043",
      "number": 43,
      "round": "Rodada 2",
      "group": "Grupo I",
      "date": "2026-06-22",
      "time": "21:00",
      "venue": "MetLife Stadium - EUA",
      "team1": "Noruega",
      "team2": "Senegal",
      "score1": null,
      "score2": null
    },
    {
      "id": "J044",
      "number": 44,
      "round": "Rodada 2",
      "group": "Grupo J",
      "date": "2026-06-23",
      "time": "00:00",
      "venue": "Levi's Stadium - EUA",
      "team1": "Jordânia",
      "team2": "Argélia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J045",
      "number": 45,
      "round": "Rodada 2",
      "group": "Grupo K",
      "date": "2026-06-23",
      "time": "14:00",
      "venue": "NRG Stadium - EUA",
      "team1": "Portugal",
      "team2": "Uzbequistão",
      "score1": null,
      "score2": null
    },
    {
      "id": "J046",
      "number": 46,
      "round": "Rodada 2",
      "group": "Grupo L",
      "date": "2026-06-23",
      "time": "17:00",
      "venue": "Gillette Stadium - EUA",
      "team1": "Inglaterra",
      "team2": "Gana",
      "score1": null,
      "score2": null
    },
    {
      "id": "J047",
      "number": 47,
      "round": "Rodada 2",
      "group": "Grupo L",
      "date": "2026-06-23",
      "time": "20:00",
      "venue": "BMO Field - CAN",
      "team1": "Panamá",
      "team2": "Croácia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J048",
      "number": 48,
      "round": "Rodada 2",
      "group": "Grupo K",
      "date": "2026-06-23",
      "time": "23:00",
      "venue": "Estadio Akron - MEX",
      "team1": "Colômbia",
      "team2": "RD Congo",
      "score1": null,
      "score2": null
    },
    {
      "id": "J049",
      "number": 49,
      "round": "Rodada 3",
      "group": "Grupo B",
      "date": "2026-06-24",
      "time": "16:00",
      "venue": "BC Place - CAN",
      "team1": "Suíça",
      "team2": "Canadá",
      "score1": null,
      "score2": null
    },
    {
      "id": "J050",
      "number": 50,
      "round": "Rodada 3",
      "group": "Grupo B",
      "date": "2026-06-24",
      "time": "16:00",
      "venue": "Lumen Field - EUA",
      "team1": "Bósnia",
      "team2": "Catar",
      "score1": null,
      "score2": null
    },
    {
      "id": "J051",
      "number": 51,
      "round": "Rodada 3",
      "group": "Grupo C",
      "date": "2026-06-24",
      "time": "19:00",
      "venue": "Hard Rock - EUA",
      "team1": "Escócia",
      "team2": "Brasil",
      "score1": null,
      "score2": null
    },
    {
      "id": "J052",
      "number": 52,
      "round": "Rodada 3",
      "group": "Grupo C",
      "date": "2026-06-24",
      "time": "19:00",
      "venue": "Mercedes-Benz - EUA",
      "team1": "Marrocos",
      "team2": "Haiti",
      "score1": null,
      "score2": null
    },
    {
      "id": "J053",
      "number": 53,
      "round": "Rodada 3",
      "group": "Grupo A",
      "date": "2026-06-24",
      "time": "22:00",
      "venue": "Estadio Azteca - MEX",
      "team1": "República Tcheca",
      "team2": "México",
      "score1": null,
      "score2": null
    },
    {
      "id": "J054",
      "number": 54,
      "round": "Rodada 3",
      "group": "Grupo A",
      "date": "2026-06-24",
      "time": "22:00",
      "venue": "Estadio BBVA - MEX",
      "team1": "África do Sul",
      "team2": "Coreia do Sul",
      "score1": null,
      "score2": null
    },
    {
      "id": "J055",
      "number": 55,
      "round": "Rodada 3",
      "group": "Grupo E",
      "date": "2026-06-25",
      "time": "17:00",
      "venue": "Lincoln Financial - EUA",
      "team1": "Curaçao",
      "team2": "Costa do Marfim",
      "score1": null,
      "score2": null
    },
    {
      "id": "J056",
      "number": 56,
      "round": "Rodada 3",
      "group": "Grupo E",
      "date": "2026-06-25",
      "time": "17:00",
      "venue": "MetLife Stadium - EUA",
      "team1": "Equador",
      "team2": "Alemanha",
      "score1": null,
      "score2": null
    },
    {
      "id": "J057",
      "number": 57,
      "round": "Rodada 3",
      "group": "Grupo F",
      "date": "2026-06-25",
      "time": "20:00",
      "venue": "AT&T Stadium - EUA",
      "team1": "Japão",
      "team2": "Suécia",
      "score1": null,
      "score2": null
    },
    {
      "id": "J058",
      "number": 58,
      "round": "Rodada 3",
      "group": "Grupo F",
      "date": "2026-06-25",
      "time": "20:00",
      "venue": "Arrowhead Stadium - EUA",
      "team1": "Tunísia",
      "team2": "Holanda",
      "score1": null,
      "score2": null
    },
    {
      "id": "J059",
      "number": 59,
      "round": "Rodada 3",
      "group": "Grupo D",
      "date": "2026-06-25",
      "time": "23:00",
      "venue": "SoFi Stadium - EUA",
      "team1": "Turquia",
      "team2": "Estados Unidos",
      "score1": null,
      "score2": null
    },
    {
      "id": "J060",
      "number": 60,
      "round": "Rodada 3",
      "group": "Grupo D",
      "date": "2026-06-25",
      "time": "23:00",
      "venue": "Levi's Stadium - EUA",
      "team1": "Paraguai",
      "team2": "Austrália",
      "score1": null,
      "score2": null
    },
    {
      "id": "J061",
      "number": 61,
      "round": "Rodada 3",
      "group": "Grupo I",
      "date": "2026-06-26",
      "time": "16:00",
      "venue": "Gillette Stadium - EUA",
      "team1": "Noruega",
      "team2": "França",
      "score1": null,
      "score2": null
    },
    {
      "id": "J062",
      "number": 62,
      "round": "Rodada 3",
      "group": "Grupo I",
      "date": "2026-06-26",
      "time": "16:00",
      "venue": "BMO Field - CAN",
      "team1": "Senegal",
      "team2": "Iraque",
      "score1": null,
      "score2": null
    },
    {
      "id": "J063",
      "number": 63,
      "round": "Rodada 3",
      "group": "Grupo H",
      "date": "2026-06-26",
      "time": "21:00",
      "venue": "NRG Stadium - EUA",
      "team1": "Cabo Verde",
      "team2": "Arábia Saudita",
      "score1": null,
      "score2": null
    },
    {
      "id": "J064",
      "number": 64,
      "round": "Rodada 3",
      "group": "Grupo H",
      "date": "2026-06-26",
      "time": "21:00",
      "venue": "Estadio Akron - MEX",
      "team1": "Uruguai",
      "team2": "Espanha",
      "score1": null,
      "score2": null
    },
    {
      "id": "J065",
      "number": 65,
      "round": "Rodada 3",
      "group": "Grupo G",
      "date": "2026-06-27",
      "time": "00:00",
      "venue": "Lumen Field - EUA",
      "team1": "Egito",
      "team2": "Irã",
      "score1": null,
      "score2": null
    },
    {
      "id": "J066",
      "number": 66,
      "round": "Rodada 3",
      "group": "Grupo G",
      "date": "2026-06-27",
      "time": "00:00",
      "venue": "BC Place - CAN",
      "team1": "Nova Zelândia",
      "team2": "Bélgica",
      "score1": null,
      "score2": null
    },
    {
      "id": "J067",
      "number": 67,
      "round": "Rodada 3",
      "group": "Grupo L",
      "date": "2026-06-27",
      "time": "18:00",
      "venue": "MetLife Stadium - EUA",
      "team1": "Panamá",
      "team2": "Inglaterra",
      "score1": null,
      "score2": null
    },
    {
      "id": "J068",
      "number": 68,
      "round": "Rodada 3",
      "group": "Grupo L",
      "date": "2026-06-27",
      "time": "18:00",
      "venue": "Lincoln Financial - EUA",
      "team1": "Croácia",
      "team2": "Gana",
      "score1": null,
      "score2": null
    },
    {
      "id": "J069",
      "number": 69,
      "round": "Rodada 3",
      "group": "Grupo K",
      "date": "2026-06-27",
      "time": "20:30",
      "venue": "Hard Rock - EUA",
      "team1": "Colômbia",
      "team2": "Portugal",
      "score1": null,
      "score2": null
    },
    {
      "id": "J070",
      "number": 70,
      "round": "Rodada 3",
      "group": "Grupo K",
      "date": "2026-06-27",
      "time": "20:30",
      "venue": "Mercedes-Benz - EUA",
      "team1": "RD Congo",
      "team2": "Uzbequistão",
      "score1": null,
      "score2": null
    },
    {
      "id": "J071",
      "number": 71,
      "round": "Rodada 3",
      "group": "Grupo J",
      "date": "2026-06-27",
      "time": "23:00",
      "venue": "Arrowhead Stadium - EUA",
      "team1": "Argélia",
      "team2": "Áustria",
      "score1": null,
      "score2": null
    },
    {
      "id": "J072",
      "number": 72,
      "round": "Rodada 3",
      "group": "Grupo J",
      "date": "2026-06-27",
      "time": "23:00",
      "venue": "AT&T Stadium - EUA",
      "team1": "Jordânia",
      "team2": "Argentina",
      "score1": null,
      "score2": null
    },
    {
      "id": "J073",
      "number": 73,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-06-28",
      "time": "16:00",
      "venue": "SoFi Stadium - EUA",
      "team1": "2o Grupo A",
      "team2": "2o Grupo B",
      "score1": null,
      "score2": null
    },
    {
      "id": "J074",
      "number": 74,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-06-29",
      "time": "17:30",
      "venue": "Gillette Stadium - EUA",
      "team1": "1o Grupo E",
      "team2": "3o melhor A/B/C/D/F",
      "score1": null,
      "score2": null
    },
    {
      "id": "J075",
      "number": 75,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-06-29",
      "time": "22:00",
      "venue": "Estadio BBVA - MEX",
      "team1": "1o Grupo F",
      "team2": "2o Grupo C",
      "score1": null,
      "score2": null
    },
    {
      "id": "J076",
      "number": 76,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-06-29",
      "time": "14:00",
      "venue": "NRG Stadium - EUA",
      "team1": "1o Grupo C",
      "team2": "2o Grupo F",
      "score1": null,
      "score2": null
    },
    {
      "id": "J077",
      "number": 77,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-06-30",
      "time": "18:00",
      "venue": "MetLife Stadium - EUA",
      "team1": "1o Grupo I",
      "team2": "3o melhor C/D/F/G/H",
      "score1": null,
      "score2": null
    },
    {
      "id": "J078",
      "number": 78,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-06-30",
      "time": "14:00",
      "venue": "AT&T Stadium - EUA",
      "team1": "2o Grupo E",
      "team2": "2o Grupo I",
      "score1": null,
      "score2": null
    },
    {
      "id": "J079",
      "number": 79,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-06-30",
      "time": "22:00",
      "venue": "Estadio Azteca - MEX",
      "team1": "1o Grupo A",
      "team2": "3o melhor C/E/F/H/I",
      "score1": null,
      "score2": null
    },
    {
      "id": "J080",
      "number": 80,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-07-01",
      "time": "13:00",
      "venue": "Mercedes-Benz - EUA",
      "team1": "1o Grupo L",
      "team2": "3o melhor E/H/I/J/K",
      "score1": null,
      "score2": null
    },
    {
      "id": "J081",
      "number": 81,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-07-01",
      "time": "21:00",
      "venue": "Levi's Stadium - EUA",
      "team1": "1o Grupo D",
      "team2": "3o melhor B/E/F/I/J",
      "score1": null,
      "score2": null
    },
    {
      "id": "J082",
      "number": 82,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-07-01",
      "time": "17:00",
      "venue": "Lumen Field - EUA",
      "team1": "1o Grupo G",
      "team2": "3o melhor A/E/H/I/J",
      "score1": null,
      "score2": null
    },
    {
      "id": "J083",
      "number": 83,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-07-02",
      "time": "20:00",
      "venue": "BMO Field - CAN",
      "team1": "2o Grupo K",
      "team2": "2o Grupo L",
      "score1": null,
      "score2": null
    },
    {
      "id": "J084",
      "number": 84,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-07-02",
      "time": "16:00",
      "venue": "SoFi Stadium - EUA",
      "team1": "1o Grupo H",
      "team2": "2o Grupo J",
      "score1": null,
      "score2": null
    },
    {
      "id": "J085",
      "number": 85,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-07-03",
      "time": "00:00",
      "venue": "BC Place - CAN",
      "team1": "1o Grupo B",
      "team2": "3o melhor E/F/G/I/J",
      "score1": null,
      "score2": null
    },
    {
      "id": "J086",
      "number": 86,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-07-03",
      "time": "19:00",
      "venue": "Hard Rock - EUA",
      "team1": "1o Grupo J",
      "team2": "2o Grupo H",
      "score1": null,
      "score2": null
    },
    {
      "id": "J087",
      "number": 87,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-07-03",
      "time": "22:30",
      "venue": "Arrowhead Stadium - EUA",
      "team1": "1o Grupo K",
      "team2": "3o melhor D/E/I/J/L",
      "score1": null,
      "score2": null
    },
    {
      "id": "J088",
      "number": 88,
      "round": "Rodada 4",
      "group": "16 avos",
      "date": "2026-07-03",
      "time": "15:00",
      "venue": "AT&T Stadium - EUA",
      "team1": "2o Grupo D",
      "team2": "2o Grupo G",
      "score1": null,
      "score2": null
    },
    {
      "id": "J089",
      "number": 89,
      "round": "Rodada 5",
      "group": "Oitavas",
      "date": "2026-07-04",
      "time": "18:00",
      "venue": "Lincoln Financial - EUA",
      "team1": "Vencedor Jogo 74",
      "team2": "Vencedor Jogo 77",
      "score1": null,
      "score2": null
    },
    {
      "id": "J090",
      "number": 90,
      "round": "Rodada 5",
      "group": "Oitavas",
      "date": "2026-07-04",
      "time": "14:00",
      "venue": "NRG Stadium - EUA",
      "team1": "Vencedor Jogo 73",
      "team2": "Vencedor Jogo 75",
      "score1": null,
      "score2": null
    },
    {
      "id": "J091",
      "number": 91,
      "round": "Rodada 5",
      "group": "Oitavas",
      "date": "2026-07-05",
      "time": "17:00",
      "venue": "MetLife Stadium - EUA",
      "team1": "Vencedor Jogo 76",
      "team2": "Vencedor Jogo 78",
      "score1": null,
      "score2": null
    },
    {
      "id": "J092",
      "number": 92,
      "round": "Rodada 5",
      "group": "Oitavas",
      "date": "2026-07-05",
      "time": "21:00",
      "venue": "Estadio Azteca - MEX",
      "team1": "Vencedor Jogo 79",
      "team2": "Vencedor Jogo 80",
      "score1": null,
      "score2": null
    },
    {
      "id": "J093",
      "number": 93,
      "round": "Rodada 5",
      "group": "Oitavas",
      "date": "2026-07-06",
      "time": "16:00",
      "venue": "AT&T Stadium - EUA",
      "team1": "Vencedor Jogo 83",
      "team2": "Vencedor Jogo 84",
      "score1": null,
      "score2": null
    },
    {
      "id": "J094",
      "number": 94,
      "round": "Rodada 5",
      "group": "Oitavas",
      "date": "2026-07-06",
      "time": "21:00",
      "venue": "Lumen Field - EUA",
      "team1": "Vencedor Jogo 81",
      "team2": "Vencedor Jogo 82",
      "score1": null,
      "score2": null
    },
    {
      "id": "J095",
      "number": 95,
      "round": "Rodada 5",
      "group": "Oitavas",
      "date": "2026-07-07",
      "time": "13:00",
      "venue": "Mercedes-Benz - EUA",
      "team1": "Vencedor Jogo 86",
      "team2": "Vencedor Jogo 88",
      "score1": null,
      "score2": null
    },
    {
      "id": "J096",
      "number": 96,
      "round": "Rodada 5",
      "group": "Oitavas",
      "date": "2026-07-07",
      "time": "17:00",
      "venue": "BC Place - CAN",
      "team1": "Vencedor Jogo 85",
      "team2": "Vencedor Jogo 87",
      "score1": null,
      "score2": null
    },
    {
      "id": "J097",
      "number": 97,
      "round": "Rodada 6",
      "group": "Quartas",
      "date": "2026-07-09",
      "time": "17:00",
      "venue": "Gillette Stadium - EUA",
      "team1": "Vencedor Jogo 89",
      "team2": "Vencedor Jogo 90",
      "score1": null,
      "score2": null
    },
    {
      "id": "J098",
      "number": 98,
      "round": "Rodada 6",
      "group": "Quartas",
      "date": "2026-07-10",
      "time": "16:00",
      "venue": "SoFi Stadium - EUA",
      "team1": "Vencedor Jogo 93",
      "team2": "Vencedor Jogo 94",
      "score1": null,
      "score2": null
    },
    {
      "id": "J099",
      "number": 99,
      "round": "Rodada 6",
      "group": "Quartas",
      "date": "2026-07-11",
      "time": "18:00",
      "venue": "Hard Rock - EUA",
      "team1": "Vencedor Jogo 91",
      "team2": "Vencedor Jogo 92",
      "score1": null,
      "score2": null
    },
    {
      "id": "J100",
      "number": 100,
      "round": "Rodada 6",
      "group": "Quartas",
      "date": "2026-07-11",
      "time": "22:00",
      "venue": "Arrowhead Stadium - EUA",
      "team1": "Vencedor Jogo 95",
      "team2": "Vencedor Jogo 96",
      "score1": null,
      "score2": null
    },
    {
      "id": "J101",
      "number": 101,
      "round": "Rodada 7",
      "group": "Semifinal",
      "date": "2026-07-14",
      "time": "16:00",
      "venue": "AT&T Stadium - EUA",
      "team1": "Vencedor Jogo 97",
      "team2": "Vencedor Jogo 98",
      "score1": null,
      "score2": null
    },
    {
      "id": "J102",
      "number": 102,
      "round": "Rodada 7",
      "group": "Semifinal",
      "date": "2026-07-15",
      "time": "16:00",
      "venue": "Mercedes-Benz - EUA",
      "team1": "Vencedor Jogo 99",
      "team2": "Vencedor Jogo 100",
      "score1": null,
      "score2": null
    },
    {
      "id": "J103",
      "number": 103,
      "round": "Rodada 8",
      "group": "3o lugar",
      "date": "2026-07-18",
      "time": "18:00",
      "venue": "Hard Rock - EUA",
      "team1": "Perdedor Jogo 101",
      "team2": "Perdedor Jogo 102",
      "score1": null,
      "score2": null
    },
    {
      "id": "J104",
      "number": 104,
      "round": "Rodada 8",
      "group": "Final",
      "date": "2026-07-19",
      "time": "16:00",
      "venue": "MetLife Stadium - EUA",
      "team1": "Vencedor Jogo 101",
      "team2": "Vencedor Jogo 102",
      "score1": null,
      "score2": null
    }
  ],
  "initialPicks": []
};
